dependencies:
# - <orginization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}